export const schemas = {
	Error: {
		type: 'object',
		properties: {
			success: { type: 'boolean', example: false },
			messageCode: { type: 'string', example: 'MSG_002' },
			errors: {
				type: 'array',
				items: {
					type: 'object',
					properties: {
						field: { type: 'string' },
						message: { type: 'string' },
					},
				},
			},
		},
	},
	User: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			email: { type: 'string', example: 'user@example.com' },
			name: { type: 'string', example: 'Nguyen Van A' },
			avatar: { type: 'string', example: 'https://example.com/avatar.jpg' },
			authProvider: { type: 'string', enum: ['local', 'google'], example: 'local' },
			role: { type: 'string', enum: ['user', 'admin'], example: 'user' },
			status: { type: 'string', enum: ['active', 'locked', 'suspended'], example: 'active' },
			isActive: { type: 'boolean', example: true },
			isEmailVerified: { type: 'boolean', example: true },
			lastLogin: { type: 'string', format: 'date-time' },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	UserStatistics: {
		type: 'object',
		properties: {
			totalUsers: { type: 'number', example: 1250 },
			activeUsers: { type: 'number', example: 1100 },
			lockedUsers: { type: 'number', example: 50 },
			suspendedUsers: { type: 'number', example: 100 },
			googleUsers: { type: 'number', example: 800 },
			localUsers: { type: 'number', example: 450 },
			verifiedUsers: { type: 'number', example: 1000 },
			recentUsers: { type: 'number', example: 150 },
			usersByStatus: {
				type: 'object',
				properties: {
					active: { type: 'number', example: 1100 },
					locked: { type: 'number', example: 50 },
					suspended: { type: 'number', example: 100 },
				},
			},
			usersByProvider: {
				type: 'object',
				properties: {
					google: { type: 'number', example: 800 },
					local: { type: 'number', example: 450 },
				},
			},
		},
	},
	Survey: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			userId: { type: 'string', example: '507f1f77bcf86cd799439011' },
			level: { type: 'string', enum: ['begin', 'n5', 'n4', 'n3', 'n2up'], example: 'n3' },
			goal: { type: 'string', enum: ['jlpt', 'travel', 'work', 'school', 'hobby'], example: 'jlpt' },
			dailyTime: { type: 'string', enum: ['lt15', '15-30', '30-60', 'gt60'], example: '30-60' },
			weakAreas: {
				type: 'array',
				items: { type: 'string', enum: ['grammar', 'vocab', 'kanji', 'listen', 'read'] },
				example: ['grammar', 'kanji'],
			},
			discovery: { type: 'string', enum: ['friend', 'sns', 'search', 'other'], example: 'search' },
			discoveryNote: { type: 'string', example: 'Found via Google search' },
			freeNote: { type: 'string', example: 'Looking forward to learning Japanese' },
			completedAt: { type: 'string', format: 'date-time' },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	Quote: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			quoteVi: { type: 'string', example: 'Học tập là món quà dành cho chính bạn trong tương lai.' },
			quoteJa: { type: 'string', example: '学ぶことは、未来の自分への贈り物です。' },
			author: { type: 'string', example: 'Lão Tử' },
			category: {
				type: 'string',
				enum: ['motivation', 'learning', 'wisdom', 'perseverance', 'success'],
				example: 'learning',
			},
			isActive: { type: 'boolean', example: true },
			displayOrder: { type: 'number', example: 1 },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	Streak: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			userId: { type: 'string', example: '507f1f77bcf86cd799439011' },
			currentStreak: { type: 'number', example: 15 },
			longestStreak: { type: 'number', example: 30 },
			totalCheckIns: { type: 'number', example: 45 },
			lastCheckIn: { type: 'string', format: 'date-time' },
			freezeCount: { type: 'number', example: 2 },
			checkInHistory: {
				type: 'array',
				items: { type: 'string', format: 'date' },
			},
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	VocabularyDeck: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			titleVi: { type: 'string', example: 'Từ vựng cơ bản N5' },
			titleJa: { type: 'string', example: 'N5基本語彙' },
			descriptionVi: { type: 'string', example: 'Từ vựng cơ bản cho người mới bắt đầu' },
			descriptionJa: { type: 'string', example: '初心者向けの基本語彙' },
			level: { type: 'string', enum: ['n5', 'n4', 'n3', 'n2', 'n1'], example: 'n5' },
			wordCount: { type: 'number', example: 25 },
			displayOrder: { type: 'number', example: 1 },
			isActive: { type: 'boolean', example: true },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	Vocabulary: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			deckId: { type: 'string', example: '507f1f77bcf86cd799439011' },
			word: { type: 'string', example: '学生' },
			reading: { type: 'string', example: 'がくせい' },
			meaningVi: { type: 'string', example: 'học sinh, sinh viên' },
			meaningJa: { type: 'string', example: '学校で勉強する人' },
			exampleSentence: { type: 'string', example: '私は学生です。' },
			exampleMeaning: { type: 'string', example: 'Tôi là sinh viên.' },
			displayOrder: { type: 'number', example: 1 },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	Kana: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			character: { type: 'string', example: 'あ' },
			romaji: { type: 'string', example: 'a' },
			script: { type: 'string', enum: ['hiragana', 'katakana'], example: 'hiragana' },
			row: { type: 'string', example: 'a-row' },
			isDiacritical: { type: 'boolean', example: false },
			displayOrder: { type: 'number', example: 1 },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	KanjiDeck: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			titleVi: { type: 'string', example: 'Kanji cơ bản N5' },
			titleJa: { type: 'string', example: 'N5基本漢字' },
			descriptionVi: { type: 'string', example: 'Kanji cơ bản cho người mới bắt đầu' },
			descriptionJa: { type: 'string', example: '初心者向けの基本漢字' },
			level: { type: 'string', enum: ['n5', 'n4', 'n3', 'n2', 'n1'], example: 'n5' },
			kanjiCount: { type: 'number', example: 25 },
			displayOrder: { type: 'number', example: 1 },
			isActive: { type: 'boolean', example: true },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	Kanji: {
		type: 'object',
		properties: {
			_id: { type: 'string', example: '507f1f77bcf86cd799439011' },
			deckId: { type: 'string', example: '507f1f77bcf86cd799439011' },
			char: { type: 'string', example: '学' },
			onYomi: { type: 'string', example: 'ガク' },
			kunYomi: { type: 'string', example: 'まな.ぶ' },
			hanViet: { type: 'string', example: 'Học' },
			meaningVi: { type: 'string', example: 'học, học tập' },
			vocabJa: { type: 'string', example: '学生（がくせい）、学校（がっこう）' },
			exampleJa: { type: 'string', example: '学校で勉強します。' },
			exampleVi: { type: 'string', example: 'Học ở trường.' },
			displayOrder: { type: 'number', example: 1 },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
};
